def compDNA(seq):
    reverseDNA = {"A":"T", "C":"G", "G":"C", "T":"A"}
    string2 = ""
    for nuc in seq:
        string = reverseDNA[nuc]
        string2 +=string
    return string2[::-1]

seq = "CGATCTGAGTCGCTATTCCCTGCCTTGCAACAAGATACTTGAGTTTCGAGCTCCTTAGAATACTAGCGCTAAAGTGCACTGACGTATTACTCGCTGGTGACCCTACCAAGCTGTAAGCTTCTTGCCTCCTCCAGCGAACGAGTCGGGTATGGTACACGAATAAAAGACGCCCGAGGCACGAAACAGATTGAAACCACTCGACAACTCAGAAATAGCTTTCACAACGCGATTGAAATAGAGCGTTCCCCCGATGTTATTATTTGGACCTTCGGCTTTTCTGTCAATGACAGCACCCAACTGCAATCCGGGTCGGTCGTTTTCCAGCAATTGAGTGCACTGTGTAGTTGGTGGCATGCTGTTAGAAGTAAGGCTGACCCAGGGAGGCGTCGCGCTATAACACACACTACACATGACGAAAACGGGCACCAGTTTCGATATAGGGCATTACCACGTTGAGATGTCTAGTGCGAGTTTAGAGCATCGCCTTCAATAACTAGATTCGTAGACAGTCTGAACACCGCTTGCTCCCTAGATGAGATTAACAGAAACCAAATGACATCACCGTGCTTATGGGTTCATTGTTTTATTAATGGCTTGTCTCAAAAAGCGCTATTACCGGGAAAACTAGGACTCACGTGCTCTCAGTGTGCTAAGTCATTATGGCATAAAGTCCCCACAGTCGCTTCTATCAACCAGATCCTCTCAGGAGTACAGGGACCTAACTCCGATATCGCGGGCCCGTCAGAGCCTGCCCTGTTTGGACCATATTGTTCGGAGACCTACGTGCATATTTCGTTTTATAGGAGACGTATTGAACCACTCCCAGGAAGAGGGTTACCCTGCCCATACG"

print(compDNA(seq))